'use client'

import Link from 'next/link'
import { motion } from 'framer-motion'
import {
  Crown, Map, BookOpen, Bot, Flame, Users, LayoutDashboard,
  ArrowRight, Check, Star, Zap, Shield, TrendingUp, ChevronRight,
  Play, Sparkles
} from 'lucide-react'

// ──────────────────────────────────────────
// Data
// ──────────────────────────────────────────
const features = [
  {
    icon: LayoutDashboard,
    title: 'CEO Dashboard',
    description: 'Track streaks, tasks, revenue goals, and daily progress at a glance.',
    color: 'text-gold-600',
    bg: 'bg-gold-100',
  },
  {
    icon: Map,
    title: 'Startup Roadmaps',
    description: '6 step-by-step paths with milestones, checklists, and unlockable lessons.',
    color: 'text-purple-600',
    bg: 'bg-purple-50',
  },
  {
    icon: BookOpen,
    title: 'Resource Vault',
    description: '200+ templates, scripts, AI prompts, supplier lists, and branding guides.',
    color: 'text-blue-600',
    bg: 'bg-blue-50',
  },
  {
    icon: Bot,
    title: 'AI Business Assistant',
    description: 'Ask anything  -  content ideas, marketing strategy, startup advice, and more.',
    color: 'text-emerald-600',
    bg: 'bg-emerald-50',
  },
  {
    icon: Flame,
    title: 'Habit Tracker',
    description: 'Build daily CEO habits: posting, outreach, learning, mindset, and fitness.',
    color: 'text-orange-600',
    bg: 'bg-orange-50',
  },
  {
    icon: Users,
    title: 'Founder Community',
    description: 'Share wins, get accountability, and connect with founders who get it.',
    color: 'text-pink-600',
    bg: 'bg-pink-50',
  },
]

const roadmaps = [
  { icon: '🛍️', title: 'Shopify Brand', weeks: 12, steps: 48 },
  { icon: '💆‍♀️', title: 'Med Spa / Wellness', weeks: 16, steps: 52 },
  { icon: '💻', title: 'Digital Products', weeks: 8, steps: 36 },
  { icon: '🔗', title: 'Affiliate Marketing', weeks: 6, steps: 28 },
  { icon: '🎥', title: 'Content Creator', weeks: 10, steps: 40 },
  { icon: '✨', title: 'Service Business', weeks: 6, steps: 32 },
]

const testimonials = [
  {
    name: 'Amara J.',
    handle: '@amaraceo',
    business: 'Shopify brand  -  $12K/mo',
    avatar: 'AJ',
    content: 'I went from no clue to $12K/month in 7 months using the Shopify roadmap. The step-by-step format finally made it click for me.',
    stars: 5,
  },
  {
    name: 'Priya S.',
    handle: '@priyabuilds',
    business: 'Digital products  -  $4K/mo',
    avatar: 'PS',
    content: 'The AI assistant alone is worth it. I use it daily for content ideas and it never runs out of angles. The habit tracker keeps me consistent.',
    stars: 5,
  },
  {
    name: 'Destiny M.',
    handle: '@destinymakesmoney',
    business: 'Service agency  -  $8K/mo',
    avatar: 'DM',
    content: 'Honestly this app made me take myself seriously as a CEO. The dashboard, the streaks, the community  -  it all works together to keep you moving.',
    stars: 5,
  },
]

const pricingPlans = [
  {
    name: 'Starter',
    price: 0,
    description: 'Perfect to get started',
    badge: null,
    features: [
      '1 Startup Roadmap',
      'CEO Dashboard',
      'Basic Habit Tracker',
      '10 Vault Resources',
      'Community Access',
    ],
    cta: 'Start Free',
    highlighted: false,
  },
  {
    name: 'Founder',
    price: 19,
    description: 'For serious builders',
    badge: 'Most Popular',
    features: [
      'All 6 Startup Roadmaps',
      'Full Resource Vault (200+)',
      'AI Assistant  -  100 queries/mo',
      'Revenue Tracker',
      'Advanced Habit Tracker',
      'Weekly Goal Setting',
      'Priority Community Badge',
    ],
    cta: 'Start 7-Day Free Trial',
    highlighted: true,
  },
  {
    name: 'CEO',
    price: 49,
    description: 'For empire builders',
    badge: 'Best Value',
    features: [
      'Everything in Founder',
      'Unlimited AI Queries',
      'Custom AI Business Plan',
      'Live Group Coaching',
      'CEO-Only Templates',
      'Supplier & Vendor Directory',
      'Private CEO Community',
    ],
    cta: 'Go CEO',
    highlighted: false,
  },
]

const stats = [
  { value: '12,400+', label: 'Founders enrolled' },
  { value: '$2.8M+', label: 'Revenue generated by members' },
  { value: '94%', label: 'Complete their first roadmap' },
  { value: '4.9 ★', label: 'Average app rating' },
]

// ──────────────────────────────────────────
// Animation helpers
// ──────────────────────────────────────────
const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  show: { opacity: 1, y: 0 },
}

const stagger = {
  hidden: {},
  show: { transition: { staggerChildren: 0.1 } },
}

// ──────────────────────────────────────────
// Navbar
// ──────────────────────────────────────────
function Navbar() {
  return (
    <header className="fixed top-0 left-0 right-0 z-50 bg-cream-50/90 backdrop-blur-md border-b border-cream-200">
      <nav className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
        <Link href="/" className="flex items-center gap-2">
          <Crown className="w-4 h-4 text-brand-500" />
          <span className="font-display font-semibold text-sm text-ink-900 tracking-tight">Rinse & Repeat CEO</span>
        </Link>

        <div className="hidden md:flex items-center gap-8">
          {['Features', 'Roadmaps', 'Pricing'].map(label => (
            <Link key={label} href={`#${label.toLowerCase()}`} className="text-sm text-ink-400 hover:text-ink-900 transition-colors">
              {label}
            </Link>
          ))}
        </div>

        <div className="flex items-center gap-4">
          <Link href="/login" className="text-sm text-ink-400 hover:text-ink-900 transition-colors hidden sm:block">
            Sign in
          </Link>
          <Link href="/signup" className="btn-gold text-sm py-2 px-5">
            Get started
          </Link>
        </div>
      </nav>
    </header>
  )
}

// ──────────────────────────────────────────
// Hero
// ──────────────────────────────────────────
function Hero() {
  return (
    <section className="pt-32 pb-24 px-6 bg-cream-50">
      <div className="max-w-6xl mx-auto grid lg:grid-cols-2 gap-20 items-center">
        {/* Left: Copy */}
        <motion.div
          variants={stagger}
          initial="hidden"
          animate="show"
          className="space-y-8"
        >
          <motion.p variants={fadeUp} className="text-xs font-semibold text-brand-500 uppercase tracking-widest">
            For women building their future
          </motion.p>

          <motion.h1
            variants={fadeUp}
            className="font-display text-5xl sm:text-6xl font-bold text-ink-900 leading-[1.08] tracking-tight"
          >
            Your CEO era<br />starts here.
          </motion.h1>

          <motion.p variants={fadeUp} className="text-lg text-ink-500 leading-relaxed max-w-md">
            Step-by-step roadmaps, an AI business assistant, habit tracking, and a resource vault  -  everything you need to build a real business.
          </motion.p>

          <motion.div variants={fadeUp} className="flex flex-col sm:flex-row gap-3">
            <Link href="/signup" className="btn-gold text-sm py-3 px-7 inline-flex items-center gap-2">
              Start for free <ArrowRight className="w-4 h-4" />
            </Link>
            <Link href="/quiz" className="btn-outline text-sm py-3 px-7 inline-flex items-center gap-2">
              Find my business match
            </Link>
          </motion.div>

          <motion.p variants={fadeUp} className="text-xs text-ink-400">
            Free plan available · No credit card required
          </motion.p>
        </motion.div>

        {/* Right: App mockup */}
        <motion.div
          initial={{ opacity: 0, y: 32 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="relative hidden lg:block"
        >
          <div className="relative mx-auto max-w-sm">

            {/* Main card */}
            <div className="relative bg-white rounded-3xl shadow-modal border border-ink-100 overflow-hidden">
              {/* Dashboard header */}
              <div className="bg-gradient-to-br from-ink-900 to-ink-800 px-6 py-5 text-white">
                <div className="flex items-center justify-between mb-4">
                  <div>
                    <p className="text-xs text-ink-300">Good morning,</p>
                    <h3 className="font-display font-bold text-lg">Jessica 👋</h3>
                  </div>
                  <div className="streak-badge bg-amber-400/20 text-amber-300 border-amber-400/30">
                    🔥 7-day streak
                  </div>
                </div>
                <div className="grid grid-cols-3 gap-2">
                  {[
                    { label: 'Tasks', value: '3/5' },
                    { label: 'XP Today', value: '+75' },
                    { label: 'Revenue', value: '$2.4K' },
                  ].map(stat => (
                    <div key={stat.label} className="bg-white/10 rounded-xl px-3 py-2 text-center">
                      <p className="font-bold text-sm">{stat.value}</p>
                      <p className="text-[10px] text-ink-300">{stat.label}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Today's task */}
              <div className="px-6 py-4 border-b border-ink-50">
                <p className="text-[10px] font-bold text-ink-400 uppercase tracking-widest mb-2">Today's CEO Task</p>
                <div className="flex items-start gap-3">
                  <div className="w-8 h-8 rounded-xl bg-gold-100 flex items-center justify-center flex-shrink-0">
                    <span className="text-base">📸</span>
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-semibold text-ink-900 leading-snug">Post your brand intro on Instagram</p>
                    <p className="text-xs text-ink-400 mt-0.5">+25 XP when complete</p>
                  </div>
                </div>
                <button className="w-full mt-3 py-2 bg-ink-900 text-white text-xs font-semibold rounded-xl hover:bg-ink-800 transition-colors">
                  Mark Complete ✓
                </button>
              </div>

              {/* Roadmap progress */}
              <div className="px-6 py-4">
                <p className="text-[10px] font-bold text-ink-400 uppercase tracking-widest mb-3">Active Roadmap</p>
                <div className="flex items-center gap-3 mb-2">
                  <span className="text-xl">🛍️</span>
                  <div className="flex-1">
                    <p className="text-sm font-semibold text-ink-900">Shopify Brand</p>
                    <p className="text-xs text-ink-400">Step 5 of 48 • Foundation phase</p>
                  </div>
                </div>
                <div className="h-2 bg-ink-100 rounded-full overflow-hidden">
                  <motion.div
                    className="h-full bg-gold-500 rounded-full"
                    initial={{ width: 0 }}
                    animate={{ width: '18%' }}
                    transition={{ duration: 1.2, delay: 0.5, ease: [0.22, 1, 0.36, 1] }}
                  />
                </div>
                <p className="text-xs text-ink-400 mt-1">18% complete</p>
              </div>
            </div>

            {/* Floating streak card */}
            <motion.div
              animate={{ y: [0, -6, 0] }}
              transition={{ duration: 3, repeat: Infinity, ease: 'easeInOut' }}
              className="absolute -top-4 -right-8 bg-white rounded-2xl shadow-elevated border border-ink-100 px-4 py-3"
            >
              <div className="flex items-center gap-2">
                <span className="text-2xl">🔥</span>
                <div>
                  <p className="text-xs font-bold text-ink-900">7-day streak!</p>
                  <p className="text-[10px] text-ink-400">Keep it going</p>
                </div>
              </div>
            </motion.div>

            {/* Floating XP card */}
            <motion.div
              animate={{ y: [0, 6, 0] }}
              transition={{ duration: 3.5, repeat: Infinity, ease: 'easeInOut', delay: 0.5 }}
              className="absolute -bottom-4 -left-8 bg-white rounded-2xl shadow-elevated border border-ink-100 px-4 py-3"
            >
              <div className="flex items-center gap-2">
                <div className="w-7 h-7 rounded-lg bg-gold-100 flex items-center justify-center">
                  <Zap className="w-3.5 h-3.5 text-gold-600" />
                </div>
                <div>
                  <p className="text-xs font-bold text-gold-700">+50 XP earned!</p>
                  <p className="text-[10px] text-ink-400">Milestone complete</p>
                </div>
              </div>
            </motion.div>
          </div>
        </motion.div>
      </div>

      {/* Scroll indicator */}
      <motion.div
        animate={{ y: [0, 8, 0] }}
        transition={{ duration: 1.5, repeat: Infinity }}
        className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-1"
      >
        <div className="w-6 h-9 rounded-full border-2 border-ink-300 flex items-start justify-center pt-1.5">
          <div className="w-1 h-2 bg-ink-400 rounded-full" />
        </div>
      </motion.div>
    </section>
  )
}

// ──────────────────────────────────────────
// Stats Bar
// ──────────────────────────────────────────
function StatsBar() {
  return (
    <section className="border-y border-cream-200 bg-white py-10">
      <div className="max-w-6xl mx-auto px-6 grid grid-cols-2 md:grid-cols-4 gap-8">
        {stats.map((stat, i) => (
          <motion.div
            key={stat.label}
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.08 }}
            className="text-center"
          >
            <p className="font-display text-3xl font-bold text-ink-900 mb-1">{stat.value}</p>
            <p className="text-sm text-ink-400">{stat.label}</p>
          </motion.div>
        ))}
      </div>
    </section>
  )
}

// ──────────────────────────────────────────
// Features
// ──────────────────────────────────────────
function Features() {
  return (
    <section id="features" className="py-24 px-6 bg-white">
      <div className="max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-14"
        >
          <p className="text-xs font-semibold text-brand-500 uppercase tracking-widest mb-4">What's inside</p>
          <h2 className="font-display text-4xl font-bold text-ink-900 mb-4 max-w-lg">
            Everything you need to build.
          </h2>
          <p className="text-base text-ink-400 max-w-md leading-relaxed">
            Six tools designed to take you from idea to income  -  all in one place.
          </p>
        </motion.div>

        <motion.div
          variants={stagger}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true }}
          className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6"
        >
          {features.map(feature => {
            const Icon = feature.icon
            return (
              <motion.div
                key={feature.title}
                variants={fadeUp}
                className="card card-hover p-6 group"
              >
                <div className={`w-11 h-11 rounded-2xl ${feature.bg} flex items-center justify-center mb-4 group-hover:scale-110 transition-transform`}>
                  <Icon className={`w-5 h-5 ${feature.color}`} />
                </div>
                <h3 className="font-display font-bold text-lg text-ink-900 mb-2">{feature.title}</h3>
                <p className="text-sm text-ink-500 leading-relaxed">{feature.description}</p>
              </motion.div>
            )
          })}
        </motion.div>
      </div>
    </section>
  )
}

// ──────────────────────────────────────────
// Roadmaps
// ──────────────────────────────────────────
function Roadmaps() {
  return (
    <section id="roadmaps" className="py-24 px-6 bg-cream-50">
      <div className="max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <span className="badge-ink mb-4 inline-flex">6 complete roadmaps</span>
          <h2 className="font-display text-4xl sm:text-5xl font-bold text-ink-900 mb-4">
            Pick your path. <span className="text-gradient-gold">Follow the map.</span>
          </h2>
          <p className="text-lg text-ink-500 max-w-xl mx-auto">
            No more Googling. Each roadmap breaks your business down into phases, milestones, and daily actions.
          </p>
        </motion.div>

        <motion.div
          variants={stagger}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true }}
          className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5"
        >
          {roadmaps.map(roadmap => (
            <motion.div
              key={roadmap.title}
              variants={fadeUp}
              className="card card-hover p-6 cursor-pointer group"
            >
              <div className="flex items-start justify-between mb-4">
                <span className="text-4xl group-hover:scale-110 transition-transform inline-block">{roadmap.icon}</span>
                <ChevronRight className="w-4 h-4 text-ink-300 group-hover:text-ink-700 group-hover:translate-x-0.5 transition-all" />
              </div>
              <h3 className="font-display font-bold text-lg text-ink-900 mb-1">{roadmap.title}</h3>
              <div className="flex items-center gap-3 mt-2">
                <span className="badge-ink">{roadmap.weeks} weeks</span>
                <span className="badge-ink">{roadmap.steps} steps</span>
              </div>
            </motion.div>
          ))}
        </motion.div>

        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="text-center mt-10"
        >
          <Link href="/signup" className="btn-primary text-base py-3 px-8 inline-flex items-center gap-2">
            Choose your roadmap <ArrowRight className="w-4 h-4" />
          </Link>
        </motion.div>
      </div>
    </section>
  )
}

// ──────────────────────────────────────────
// How It Works
// ──────────────────────────────────────────
function HowItWorks() {
  const steps = [
    {
      number: '01',
      title: 'Build your CEO profile',
      description: 'Tell us your business type, current stage, and goals. We personalize your entire experience.',
    },
    {
      number: '02',
      title: 'Pick your roadmap',
      description: 'Choose from 6 detailed business roadmaps. Each milestone is a clear, actionable step.',
    },
    {
      number: '03',
      title: 'Complete daily CEO tasks',
      description: 'Every day you get a task, a habit to build, and XP to earn. Consistency compounds.',
    },
  ]

  return (
    <section className="py-24 px-6 bg-white">
      <div className="max-w-5xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="font-display text-4xl sm:text-5xl font-bold text-ink-900 mb-4">
            How it works
          </h2>
          <p className="text-lg text-ink-500">Simple by design. Powerful by default.</p>
        </motion.div>

        <div className="relative">
          {/* Connecting line */}
          <div className="absolute top-8 left-8 right-8 h-0.5 bg-ink-100 hidden md:block" />

          <div className="grid md:grid-cols-3 gap-10">
            {steps.map((step, i) => (
              <motion.div
                key={step.number}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.15 }}
                className="relative text-center"
              >
                <div className="w-16 h-16 rounded-2xl bg-ink-900 text-white font-display font-bold text-xl flex items-center justify-center mx-auto mb-5 relative z-10">
                  {step.number}
                </div>
                <h3 className="font-display font-bold text-lg text-ink-900 mb-2">{step.title}</h3>
                <p className="text-sm text-ink-500 leading-relaxed">{step.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}

// ──────────────────────────────────────────
// Testimonials
// ──────────────────────────────────────────
function Testimonials() {
  return (
    <section id="community" className="py-24 px-6 bg-cream-50">
      <div className="max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="font-display text-4xl sm:text-5xl font-bold text-ink-900 mb-4">
            Real founders, real results
          </h2>
          <p className="text-lg text-ink-500">They started where you are. Here's where they are now.</p>
        </motion.div>

        <motion.div
          variants={stagger}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true }}
          className="grid md:grid-cols-3 gap-6"
        >
          {testimonials.map(t => (
            <motion.div key={t.name} variants={fadeUp} className="card p-6 flex flex-col gap-4">
              <div className="flex">
                {Array.from({ length: t.stars }, (_, i) => (
                  <Star key={i} className="w-4 h-4 fill-gold-400 text-gold-400" />
                ))}
              </div>
              <p className="text-sm text-ink-700 leading-relaxed flex-1">"{t.content}"</p>
              <div className="flex items-center gap-3 pt-2 border-t border-ink-50">
                <div className="w-9 h-9 rounded-full bg-gradient-to-br from-gold-300 to-gold-500 flex items-center justify-center text-xs font-bold text-white">
                  {t.avatar}
                </div>
                <div>
                  <p className="text-sm font-semibold text-ink-900">{t.name}</p>
                  <p className="text-xs text-success-dark font-medium">{t.business}</p>
                </div>
              </div>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  )
}

// ──────────────────────────────────────────
// Stan Store Section
// ──────────────────────────────────────────
const stanFeatures = [
  {
    icon: '🛍️',
    title: 'Sell anything instantly',
    description: 'Digital products, courses, memberships, 1:1 bookings  -  all in one link.',
  },
  {
    icon: '🔗',
    title: 'One link for everything',
    description: 'Replace your Linktree, Gumroad, and Calendly with a single beautiful storefront.',
  },
  {
    icon: '💸',
    title: 'Keep more of your money',
    description: 'No monthly fees on the free plan. Stan only takes a small cut when you make a sale.',
  },
  {
    icon: '⚡',
    title: 'Set up in minutes',
    description: 'Go from zero to selling in under 10 minutes. No tech skills needed.',
  },
  {
    icon: '📧',
    title: 'Built-in email list',
    description: 'Collect emails automatically from every customer and follower  -  no Mailchimp needed.',
  },
  {
    icon: '📱',
    title: 'Made for creators',
    description: 'Works perfectly with Instagram, TikTok, and YouTube. Drop your link in bio and start earning.',
  },
]

function StanSection() {
  return (
    <section className="py-24 px-6 bg-ink-900 relative overflow-hidden">
      {/* Background glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] bg-gold-500/10 rounded-full blur-3xl pointer-events-none" />

      <div className="relative max-w-5xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-14"
        >
          <span className="inline-flex items-center gap-2 bg-gold-500/20 text-gold-300 text-xs font-bold px-4 py-2 rounded-full border border-gold-500/30 mb-5">
            ✨ A tool I personally use and love
          </span>
          <h2 className="font-display text-4xl sm:text-5xl font-bold text-white mb-4">
            Sell your first product with <span className="text-gradient-gold">Stan Store</span>
          </h2>
          <p className="text-lg text-ink-300 max-w-2xl mx-auto leading-relaxed">
            Every CEO needs a place to sell. Stan is the easiest way to turn your knowledge and content into income  -  I use it myself and it's the first tool I recommend to every founder in this community.
          </p>
        </motion.div>

        {/* Feature grid */}
        <motion.div
          variants={stagger}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true }}
          className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-12"
        >
          {stanFeatures.map(feature => (
            <motion.div
              key={feature.title}
              variants={fadeUp}
              className="bg-white/5 border border-white/10 rounded-2xl p-5 hover:bg-white/8 transition-colors"
            >
              <span className="text-3xl mb-3 block">{feature.icon}</span>
              <h3 className="font-semibold text-white text-sm mb-1.5">{feature.title}</h3>
              <p className="text-xs text-ink-300 leading-relaxed">{feature.description}</p>
            </motion.div>
          ))}
        </motion.div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center"
        >
          <div className="inline-flex flex-col items-center gap-4 bg-white/5 border border-white/10 rounded-3xl px-10 py-8">
            <p className="text-white font-semibold text-lg">Ready to start selling?</p>
            <p className="text-ink-300 text-sm max-w-sm text-center">
              Use my link to get started on Stan  -  it's free and takes less than 10 minutes to set up your storefront.
            </p>
            <a
              href="https://join.stan.store/thedit"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 bg-gold-500 hover:bg-gold-400 text-white font-bold text-sm px-8 py-3.5 rounded-xl transition-all shadow-glow hover:scale-[1.02] active:scale-[0.98]"
            >
              Start your Stan Store for free <ArrowRight className="w-4 h-4" />
            </a>
            <p className="text-xs text-ink-400">Free to start • No monthly fees • Takes 10 min</p>
          </div>
        </motion.div>
      </div>
    </section>
  )
}

// ──────────────────────────────────────────
// Pricing
// ──────────────────────────────────────────
function Pricing() {
  return (
    <section id="pricing" className="py-24 px-6 bg-white">
      <div className="max-w-5xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="font-display text-4xl sm:text-5xl font-bold text-ink-900 mb-4">
            Invest in your CEO era
          </h2>
          <p className="text-lg text-ink-500">Start free. Upgrade when you're ready to go all in.</p>
        </motion.div>

        <div className="grid md:grid-cols-3 gap-6 items-start">
          {pricingPlans.map((plan, i) => (
            <motion.div
              key={plan.name}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className={`rounded-3xl border p-8 relative flex flex-col ${
                plan.highlighted
                  ? 'bg-ink-900 border-ink-900 text-white shadow-modal scale-105'
                  : 'bg-white border-ink-100 card'
              }`}
            >
              {plan.badge && (
                <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                  <span className="bg-gold-500 text-white text-xs font-bold px-3 py-1 rounded-full whitespace-nowrap">
                    {plan.badge}
                  </span>
                </div>
              )}

              <div className="mb-6">
                <h3 className={`font-display font-bold text-xl mb-1 ${plan.highlighted ? 'text-white' : 'text-ink-900'}`}>
                  {plan.name}
                </h3>
                <p className={`text-sm mb-4 ${plan.highlighted ? 'text-ink-300' : 'text-ink-500'}`}>{plan.description}</p>
                <div className="flex items-baseline gap-1">
                  <span className={`font-display text-4xl font-bold ${plan.highlighted ? 'text-white' : 'text-ink-900'}`}>
                    ${plan.price}
                  </span>
                  <span className={`text-sm ${plan.highlighted ? 'text-ink-300' : 'text-ink-400'}`}>/month</span>
                </div>
              </div>

              <ul className="space-y-3 mb-8 flex-1">
                {plan.features.map(feature => (
                  <li key={feature} className="flex items-start gap-2.5">
                    <div className={`w-4 h-4 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5 ${
                      plan.highlighted ? 'bg-gold-500' : 'bg-success-light'
                    }`}>
                      <Check className={`w-2.5 h-2.5 ${plan.highlighted ? 'text-white' : 'text-success'}`} strokeWidth={3} />
                    </div>
                    <span className={`text-sm ${plan.highlighted ? 'text-ink-200' : 'text-ink-600'}`}>{feature}</span>
                  </li>
                ))}
              </ul>

              <Link
                href="/signup"
                className={`w-full text-center py-3 px-6 rounded-xl text-sm font-bold transition-all ${
                  plan.highlighted
                    ? 'bg-gold-500 text-white hover:bg-gold-400'
                    : 'bg-ink-900 text-white hover:bg-ink-800'
                }`}
              >
                {plan.cta}
              </Link>
            </motion.div>
          ))}
        </div>

        <p className="text-center text-sm text-ink-400 mt-8">
          All plans include a 7-day free trial. Cancel anytime. No hidden fees.
        </p>
      </div>
    </section>
  )
}

// ──────────────────────────────────────────
// Final CTA
// ──────────────────────────────────────────
function FinalCTA() {
  return (
    <section className="py-24 px-6 bg-ink-900">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        className="max-w-2xl mx-auto text-center"
      >
        <Crown className="w-6 h-6 text-brand-300 mx-auto mb-6" />
        <h2 className="font-display text-4xl sm:text-5xl font-bold text-white mb-4 leading-tight tracking-tight">
          Ready to build?
        </h2>
        <p className="text-base text-ink-300 mb-8 leading-relaxed">
          Join 12,400+ founders. Start free  -  no credit card required.
        </p>
        <Link href="/signup" className="btn-gold inline-flex items-center gap-2 text-sm py-3 px-8">
          Get started free <ArrowRight className="w-4 h-4" />
        </Link>
      </motion.div>
    </section>
  )
}

// ──────────────────────────────────────────
// Footer
// ──────────────────────────────────────────
function Footer() {
  return (
    <footer className="bg-ink-950 py-12 px-6">
      <div className="max-w-7xl mx-auto">
        <div className="flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-gold-400 to-gold-600 flex items-center justify-center">
              <Crown className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="font-display font-bold text-sm text-white">Rinse & Repeat CEO</span>
          </div>
          <div className="flex items-center gap-6">
            {['Privacy', 'Terms', 'Support', 'Instagram', 'TikTok'].map(link => (
              <Link key={link} href="#" className="text-xs text-ink-400 hover:text-ink-200 transition-colors">
                {link}
              </Link>
            ))}
          </div>
          <p className="text-xs text-ink-500">© 2025 Rinse & Repeat CEO. All rights reserved.</p>
        </div>
      </div>
    </footer>
  )
}

// ──────────────────────────────────────────
// Page
// ──────────────────────────────────────────
export default function LandingPage() {
  return (
    <main>
      <Navbar />
      <Hero />
      <StatsBar />
      <Features />
      <Roadmaps />
      <HowItWorks />
      <Testimonials />
      <StanSection />
      <Pricing />
      <FinalCTA />
      <Footer />
    </main>
  )
}
